[build]
  functions = "netlify/functions"
  publish   = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200